### ISSUE TITLE
Tiny spikes visible for sharp angles

### ISSUE THREAD

**Issue by montaga** [IMAGINARY/durden#1]
I noticed that if the angles get very sharp then tiny spikes become visible.

![image](https://user-images.githubusercontent.com/15124152/66550114-f7404a80-eb44-11e9-82f2-28f0ad3172ce.png)

A possible fix might be to use [path.strokeJoin = 'round';](http://paperjs.org/reference/item/#strokejoin) instead of 'miter'.

**Comment by porst17** [comment]
Thanks for reporting!

Probably, `bevel` is a better option because it just adds another edge instead of an arc (which is more expensive to compute).

**Comment by elondaits** [comment]
Fixed with `bevel` in 7dac05cb4371b06b95b7d292d4ff86e86fcc4068 and published as v1.0.2. Thanks!
